// Blackboard payload schema — M8 多 Agent 协调黑板消息格式。
// 架构文档: docs/arch/08-Multi-Agent-Orchestrator-深度选型.md §1

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: blackboard.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BlackboardEvent 是黑板上发布的结构化事件。
// 禁止 P2P 自然语言协调——自然语言仅作 payload content。
type BlackboardEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "task_posted" | "claimed" | "reaped" | "completed" | "failed" |
	// "agent_registered" | "agent_deregistered" | "co_evolution" | "topology_change"
	TaskId        string `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentId       string `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Payload       []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Timestamp     int64  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                          // Unix microseconds
	TraceContext  []byte `protobuf:"bytes,6,opt,name=trace_context,json=traceContext,proto3" json:"trace_context,omitempty"` // OTel W3C Trace Context
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlackboardEvent) Reset() {
	*x = BlackboardEvent{}
	mi := &file_blackboard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlackboardEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlackboardEvent) ProtoMessage() {}

func (x *BlackboardEvent) ProtoReflect() protoreflect.Message {
	mi := &file_blackboard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlackboardEvent.ProtoReflect.Descriptor instead.
func (*BlackboardEvent) Descriptor() ([]byte, []int) {
	return file_blackboard_proto_rawDescGZIP(), []int{0}
}

func (x *BlackboardEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BlackboardEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *BlackboardEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *BlackboardEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BlackboardEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BlackboardEvent) GetTraceContext() []byte {
	if x != nil {
		return x.TraceContext
	}
	return nil
}

// TaskIntent 是发布到黑板的任务意图。
type TaskIntent struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Goal                 string                 `protobuf:"bytes,1,opt,name=goal,proto3" json:"goal,omitempty"`
	TaskType             string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Priority             int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"` // 0=最高
	RequiredCapabilities []string               `protobuf:"bytes,4,rep,name=required_capabilities,json=requiredCapabilities,proto3" json:"required_capabilities,omitempty"`
	Input                []byte                 `protobuf:"bytes,5,opt,name=input,proto3" json:"input,omitempty"`        // JSON 序列化输入
	Deadline             int64                  `protobuf:"varint,6,opt,name=deadline,proto3" json:"deadline,omitempty"` // Unix microseconds
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TaskIntent) Reset() {
	*x = TaskIntent{}
	mi := &file_blackboard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskIntent) ProtoMessage() {}

func (x *TaskIntent) ProtoReflect() protoreflect.Message {
	mi := &file_blackboard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskIntent.ProtoReflect.Descriptor instead.
func (*TaskIntent) Descriptor() ([]byte, []int) {
	return file_blackboard_proto_rawDescGZIP(), []int{1}
}

func (x *TaskIntent) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *TaskIntent) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *TaskIntent) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *TaskIntent) GetRequiredCapabilities() []string {
	if x != nil {
		return x.RequiredCapabilities
	}
	return nil
}

func (x *TaskIntent) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *TaskIntent) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

// TaskResult 是任务完成结果。
type TaskResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentId        string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Success        bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Output         []byte                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Error          string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	LatencyMs      int64                  `protobuf:"varint,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	TokensConsumed int32                  `protobuf:"varint,7,opt,name=tokens_consumed,json=tokensConsumed,proto3" json:"tokens_consumed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_blackboard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_blackboard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_blackboard_proto_rawDescGZIP(), []int{2}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResult) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *TaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResult) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *TaskResult) GetTokensConsumed() int32 {
	if x != nil {
		return x.TokensConsumed
	}
	return 0
}

// AgentCard 是 Agent 能力声明（A2A v0.3 兼容格式）。
type AgentCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Skills        []string               `protobuf:"bytes,4,rep,name=skills,proto3" json:"skills,omitempty"`
	Tools         []string               `protobuf:"bytes,5,rep,name=tools,proto3" json:"tools,omitempty"`
	Models        []string               `protobuf:"bytes,6,rep,name=models,proto3" json:"models,omitempty"`
	MaxConcurrent int32                  `protobuf:"varint,7,opt,name=max_concurrent,json=maxConcurrent,proto3" json:"max_concurrent,omitempty"`
	TrustLevel    int32                  `protobuf:"varint,8,opt,name=trust_level,json=trustLevel,proto3" json:"trust_level,omitempty"`
	SandboxTier   int32                  `protobuf:"varint,9,opt,name=sandbox_tier,json=sandboxTier,proto3" json:"sandbox_tier,omitempty"`
	Endpoint      string                 `protobuf:"bytes,10,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,11,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // Ed25519
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCard) Reset() {
	*x = AgentCard{}
	mi := &file_blackboard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCard) ProtoMessage() {}

func (x *AgentCard) ProtoReflect() protoreflect.Message {
	mi := &file_blackboard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCard.ProtoReflect.Descriptor instead.
func (*AgentCard) Descriptor() ([]byte, []int) {
	return file_blackboard_proto_rawDescGZIP(), []int{3}
}

func (x *AgentCard) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentCard) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentCard) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AgentCard) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *AgentCard) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *AgentCard) GetModels() []string {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *AgentCard) GetMaxConcurrent() int32 {
	if x != nil {
		return x.MaxConcurrent
	}
	return 0
}

func (x *AgentCard) GetTrustLevel() int32 {
	if x != nil {
		return x.TrustLevel
	}
	return 0
}

func (x *AgentCard) GetSandboxTier() int32 {
	if x != nil {
		return x.SandboxTier
	}
	return 0
}

func (x *AgentCard) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *AgentCard) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

var File_blackboard_proto protoreflect.FileDescriptor

const file_blackboard_proto_rawDesc = "" +
	"\n" +
	"\x10blackboard.proto\x12\x10polaris.protocol\"\xb6\x01\n" +
	"\x0fBlackboardEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12#\n" +
	"\rtrace_context\x18\x06 \x01(\fR\ftraceContext\"\xc0\x01\n" +
	"\n" +
	"TaskIntent\x12\x12\n" +
	"\x04goal\x18\x01 \x01(\tR\x04goal\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x123\n" +
	"\x15required_capabilities\x18\x04 \x03(\tR\x14requiredCapabilities\x12\x14\n" +
	"\x05input\x18\x05 \x01(\fR\x05input\x12\x1a\n" +
	"\bdeadline\x18\x06 \x01(\x03R\bdeadline\"\xd0\x01\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x04 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x03R\tlatencyMs\x12'\n" +
	"\x0ftokens_consumed\x18\a \x01(\x05R\x0etokensConsumed\"\xc7\x02\n" +
	"\tAgentCard\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06skills\x18\x04 \x03(\tR\x06skills\x12\x14\n" +
	"\x05tools\x18\x05 \x03(\tR\x05tools\x12\x16\n" +
	"\x06models\x18\x06 \x03(\tR\x06models\x12%\n" +
	"\x0emax_concurrent\x18\a \x01(\x05R\rmaxConcurrent\x12\x1f\n" +
	"\vtrust_level\x18\b \x01(\x05R\n" +
	"trustLevel\x12!\n" +
	"\fsandbox_tier\x18\t \x01(\x05R\vsandboxTier\x12\x1a\n" +
	"\bendpoint\x18\n" +
	" \x01(\tR\bendpoint\x12\x1d\n" +
	"\n" +
	"public_key\x18\v \x01(\fR\tpublicKeyB?Z=github.com/polarisagi/polarisagi-harness/internal/protocol/pbb\x06proto3"

var (
	file_blackboard_proto_rawDescOnce sync.Once
	file_blackboard_proto_rawDescData []byte
)

func file_blackboard_proto_rawDescGZIP() []byte {
	file_blackboard_proto_rawDescOnce.Do(func() {
		file_blackboard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blackboard_proto_rawDesc), len(file_blackboard_proto_rawDesc)))
	})
	return file_blackboard_proto_rawDescData
}

var file_blackboard_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_blackboard_proto_goTypes = []any{
	(*BlackboardEvent)(nil), // 0: polaris.protocol.BlackboardEvent
	(*TaskIntent)(nil),      // 1: polaris.protocol.TaskIntent
	(*TaskResult)(nil),      // 2: polaris.protocol.TaskResult
	(*AgentCard)(nil),       // 3: polaris.protocol.AgentCard
}
var file_blackboard_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_blackboard_proto_init() }
func file_blackboard_proto_init() {
	if File_blackboard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blackboard_proto_rawDesc), len(file_blackboard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blackboard_proto_goTypes,
		DependencyIndexes: file_blackboard_proto_depIdxs,
		MessageInfos:      file_blackboard_proto_msgTypes,
	}.Build()
	File_blackboard_proto = out.File
	file_blackboard_proto_goTypes = nil
	file_blackboard_proto_depIdxs = nil
}
