// EventLog payload schema — M2 events 表 Protobuf 序列化格式。
// Go↔Rust 同 .proto 生成，约 60-80% 体积缩减 vs JSON。
// 架构文档: docs/arch/02-Storage-Fabric-深度选型.md §2.1

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: event.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event 是写入 events 表的单一事件。
// 各模块通过 EventLog.Subscribe 消费。
type Event struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`           // ULID
	Topic           string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`     // "session.*" | "skill.*" | "safety.*"
	Actor           string                 `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`     // "agent-3" | "user" | "system"
	Type            string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`       // "llm_call" | "tool_call" | "state_transition"
	Payload         []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"` // 子类型序列化 (LLMCallPayload / ToolCallPayload / ...)
	IdempotencyKey  string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	OccurredAt      int64                  `protobuf:"varint,7,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"` // TSM: Unix microseconds
	DurativeGroupId string                 `protobuf:"bytes,8,opt,name=durative_group_id,json=durativeGroupId,proto3" json:"durative_group_id,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`             // Unix microseconds
	TaintLevel      int32                  `protobuf:"varint,10,opt,name=taint_level,json=taintLevel,proto3" json:"taint_level,omitempty"`         // [TaintLevel] 0-4, field 16383 tail HMAC
	HmacSignature   []byte                 `protobuf:"bytes,11,opt,name=hmac_signature,json=hmacSignature,proto3" json:"hmac_signature,omitempty"` // SHA-256(protobuf_bytes + persistent_key)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Event) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Event) GetOccurredAt() int64 {
	if x != nil {
		return x.OccurredAt
	}
	return 0
}

func (x *Event) GetDurativeGroupId() string {
	if x != nil {
		return x.DurativeGroupId
	}
	return ""
}

func (x *Event) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Event) GetTaintLevel() int32 {
	if x != nil {
		return x.TaintLevel
	}
	return 0
}

func (x *Event) GetHmacSignature() []byte {
	if x != nil {
		return x.HmacSignature
	}
	return nil
}

// StateTransitionEvent 是 M4 FSM 状态转移事件。
type StateTransitionEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentId        string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ClaimedVersion int64                  `protobuf:"varint,3,opt,name=claimed_version,json=claimedVersion,proto3" json:"claimed_version,omitempty"`
	EventType      string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"` // "state_transition" | "tool_call" | "observation" | "reflection"
	Payload        []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StateTransitionEvent) Reset() {
	*x = StateTransitionEvent{}
	mi := &file_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateTransitionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateTransitionEvent) ProtoMessage() {}

func (x *StateTransitionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateTransitionEvent.ProtoReflect.Descriptor instead.
func (*StateTransitionEvent) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{1}
}

func (x *StateTransitionEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *StateTransitionEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StateTransitionEvent) GetClaimedVersion() int64 {
	if x != nil {
		return x.ClaimedVersion
	}
	return 0
}

func (x *StateTransitionEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *StateTransitionEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// LLMCallPayload 是 LLM 调用事件的载荷。
type LLMCallPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Model          string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Provider       string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	InputTokens    int32                  `protobuf:"varint,3,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens   int32                  `protobuf:"varint,4,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	CacheHitTokens int32                  `protobuf:"varint,5,opt,name=cache_hit_tokens,json=cacheHitTokens,proto3" json:"cache_hit_tokens,omitempty"`
	CostUsd        float64                `protobuf:"fixed64,6,opt,name=cost_usd,json=costUsd,proto3" json:"cost_usd,omitempty"`
	LatencyMs      int64                  `protobuf:"varint,7,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	FinishReason   string                 `protobuf:"bytes,8,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	RouteTier      string                 `protobuf:"bytes,9,opt,name=route_tier,json=routeTier,proto3" json:"route_tier,omitempty"` // "L1" | "L2" | "L3"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LLMCallPayload) Reset() {
	*x = LLMCallPayload{}
	mi := &file_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LLMCallPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LLMCallPayload) ProtoMessage() {}

func (x *LLMCallPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LLMCallPayload.ProtoReflect.Descriptor instead.
func (*LLMCallPayload) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{2}
}

func (x *LLMCallPayload) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *LLMCallPayload) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *LLMCallPayload) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *LLMCallPayload) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *LLMCallPayload) GetCacheHitTokens() int32 {
	if x != nil {
		return x.CacheHitTokens
	}
	return 0
}

func (x *LLMCallPayload) GetCostUsd() float64 {
	if x != nil {
		return x.CostUsd
	}
	return 0
}

func (x *LLMCallPayload) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *LLMCallPayload) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *LLMCallPayload) GetRouteTier() string {
	if x != nil {
		return x.RouteTier
	}
	return ""
}

// ToolCallPayload 是工具调用事件的载荷。
type ToolCallPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Capability    string                 `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"` // "read_only" | "write_local" | "write_network" | "privileged"
	RiskLevel     int32                  `protobuf:"varint,3,opt,name=risk_level,json=riskLevel,proto3" json:"risk_level,omitempty"`
	SandboxTier   int32                  `protobuf:"varint,4,opt,name=sandbox_tier,json=sandboxTier,proto3" json:"sandbox_tier,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"` // "builtin" | "mcp" | "skill" | "a2a"
	LatencyMs     int64                  `protobuf:"varint,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	Success       bool                   `protobuf:"varint,7,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallPayload) Reset() {
	*x = ToolCallPayload{}
	mi := &file_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallPayload) ProtoMessage() {}

func (x *ToolCallPayload) ProtoReflect() protoreflect.Message {
	mi := &file_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallPayload.ProtoReflect.Descriptor instead.
func (*ToolCallPayload) Descriptor() ([]byte, []int) {
	return file_event_proto_rawDescGZIP(), []int{3}
}

func (x *ToolCallPayload) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCallPayload) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *ToolCallPayload) GetRiskLevel() int32 {
	if x != nil {
		return x.RiskLevel
	}
	return 0
}

func (x *ToolCallPayload) GetSandboxTier() int32 {
	if x != nil {
		return x.SandboxTier
	}
	return 0
}

func (x *ToolCallPayload) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ToolCallPayload) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *ToolCallPayload) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToolCallPayload) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_event_proto protoreflect.FileDescriptor

const file_event_proto_rawDesc = "" +
	"\n" +
	"\vevent.proto\x12\x10polaris.protocol\"\xce\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\x12\x1f\n" +
	"\voccurred_at\x18\a \x01(\x03R\n" +
	"occurredAt\x12*\n" +
	"\x11durative_group_id\x18\b \x01(\tR\x0fdurativeGroupId\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vtaint_level\x18\n" +
	" \x01(\x05R\n" +
	"taintLevel\x12%\n" +
	"\x0ehmac_signature\x18\v \x01(\fR\rhmacSignature\"\xac\x01\n" +
	"\x14StateTransitionEvent\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12'\n" +
	"\x0fclaimed_version\x18\x03 \x01(\x03R\x0eclaimedVersion\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"\xb2\x02\n" +
	"\x0eLLMCallPayload\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12!\n" +
	"\finput_tokens\x18\x03 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x04 \x01(\x05R\foutputTokens\x12(\n" +
	"\x10cache_hit_tokens\x18\x05 \x01(\x05R\x0ecacheHitTokens\x12\x19\n" +
	"\bcost_usd\x18\x06 \x01(\x01R\acostUsd\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\a \x01(\x03R\tlatencyMs\x12#\n" +
	"\rfinish_reason\x18\b \x01(\tR\ffinishReason\x12\x1d\n" +
	"\n" +
	"route_tier\x18\t \x01(\tR\trouteTier\"\xf7\x01\n" +
	"\x0fToolCallPayload\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x1e\n" +
	"\n" +
	"capability\x18\x02 \x01(\tR\n" +
	"capability\x12\x1d\n" +
	"\n" +
	"risk_level\x18\x03 \x01(\x05R\triskLevel\x12!\n" +
	"\fsandbox_tier\x18\x04 \x01(\x05R\vsandboxTier\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x03R\tlatencyMs\x12\x18\n" +
	"\asuccess\x18\a \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05errorB<Z:github.com/polarisagi/polarisagi-harness/internal/protocol/pbb\x06proto3"

var (
	file_event_proto_rawDescOnce sync.Once
	file_event_proto_rawDescData []byte
)

func file_event_proto_rawDescGZIP() []byte {
	file_event_proto_rawDescOnce.Do(func() {
		file_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)))
	})
	return file_event_proto_rawDescData
}

var file_event_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_event_proto_goTypes = []any{
	(*Event)(nil),                // 0: polaris.protocol.Event
	(*StateTransitionEvent)(nil), // 1: polaris.protocol.StateTransitionEvent
	(*LLMCallPayload)(nil),       // 2: polaris.protocol.LLMCallPayload
	(*ToolCallPayload)(nil),      // 3: polaris.protocol.ToolCallPayload
}
var file_event_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_event_proto_init() }
func file_event_proto_init() {
	if File_event_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_proto_rawDesc), len(file_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_event_proto_goTypes,
		DependencyIndexes: file_event_proto_depIdxs,
		MessageInfos:      file_event_proto_msgTypes,
	}.Build()
	File_event_proto = out.File
	file_event_proto_goTypes = nil
	file_event_proto_depIdxs = nil
}
