// MutationBus payload schema — M2 DatabaseWriter 串行写格式。
// 架构文档: docs/arch/02-Storage-Fabric-深度选型.md §2.3

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: mutation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MutationIntent 是单次状态变异请求。
type MutationIntent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Table            string                 `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Operation        string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"` // "upsert" | "delete"
	Key              []byte                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Payload          []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	TaskId           string                 `protobuf:"bytes,5,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentId          string                 `protobuf:"bytes,6,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ClaimedVersion   int64                  `protobuf:"varint,7,opt,name=claimed_version,json=claimedVersion,proto3" json:"claimed_version,omitempty"`
	Priority         int32                  `protobuf:"varint,8,opt,name=priority,proto3" json:"priority,omitempty"` // 0=Normal, 1=Flush
	CompositeGroupId string                 `protobuf:"bytes,9,opt,name=composite_group_id,json=compositeGroupId,proto3" json:"composite_group_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MutationIntent) Reset() {
	*x = MutationIntent{}
	mi := &file_mutation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutationIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutationIntent) ProtoMessage() {}

func (x *MutationIntent) ProtoReflect() protoreflect.Message {
	mi := &file_mutation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutationIntent.ProtoReflect.Descriptor instead.
func (*MutationIntent) Descriptor() ([]byte, []int) {
	return file_mutation_proto_rawDescGZIP(), []int{0}
}

func (x *MutationIntent) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *MutationIntent) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *MutationIntent) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *MutationIntent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MutationIntent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *MutationIntent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MutationIntent) GetClaimedVersion() int64 {
	if x != nil {
		return x.ClaimedVersion
	}
	return 0
}

func (x *MutationIntent) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *MutationIntent) GetCompositeGroupId() string {
	if x != nil {
		return x.CompositeGroupId
	}
	return ""
}

// CompositeMutationIntent 是多表原子提交请求。
// DatabaseWriter 收集同 GroupID 成员，单 BEGIN IMMEDIATE COMMIT 原子提交。
type CompositeMutationIntent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Intents       []*MutationIntent      `protobuf:"bytes,2,rep,name=intents,proto3" json:"intents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompositeMutationIntent) Reset() {
	*x = CompositeMutationIntent{}
	mi := &file_mutation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompositeMutationIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompositeMutationIntent) ProtoMessage() {}

func (x *CompositeMutationIntent) ProtoReflect() protoreflect.Message {
	mi := &file_mutation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompositeMutationIntent.ProtoReflect.Descriptor instead.
func (*CompositeMutationIntent) Descriptor() ([]byte, []int) {
	return file_mutation_proto_rawDescGZIP(), []int{1}
}

func (x *CompositeMutationIntent) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CompositeMutationIntent) GetIntents() []*MutationIntent {
	if x != nil {
		return x.Intents
	}
	return nil
}

// OutboxRecord 是跨引擎投影任务。
type OutboxRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetEngine   string                 `protobuf:"bytes,1,opt,name=target_engine,json=targetEngine,proto3" json:"target_engine,omitempty"` // "sqlite" | "surreal"
	Operation      string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`                           // "upsert" | "delete"
	Scope          string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	Payload        []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Version        int32                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"` // 版本高水位
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OutboxRecord) Reset() {
	*x = OutboxRecord{}
	mi := &file_mutation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboxRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboxRecord) ProtoMessage() {}

func (x *OutboxRecord) ProtoReflect() protoreflect.Message {
	mi := &file_mutation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboxRecord.ProtoReflect.Descriptor instead.
func (*OutboxRecord) Descriptor() ([]byte, []int) {
	return file_mutation_proto_rawDescGZIP(), []int{2}
}

func (x *OutboxRecord) GetTargetEngine() string {
	if x != nil {
		return x.TargetEngine
	}
	return ""
}

func (x *OutboxRecord) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *OutboxRecord) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *OutboxRecord) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OutboxRecord) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *OutboxRecord) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_mutation_proto protoreflect.FileDescriptor

const file_mutation_proto_rawDesc = "" +
	"\n" +
	"\x0emutation.proto\x12\x10polaris.protocol\"\x97\x02\n" +
	"\x0eMutationIntent\x12\x14\n" +
	"\x05table\x18\x01 \x01(\tR\x05table\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x10\n" +
	"\x03key\x18\x03 \x01(\fR\x03key\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12\x17\n" +
	"\atask_id\x18\x05 \x01(\tR\x06taskId\x12\x19\n" +
	"\bagent_id\x18\x06 \x01(\tR\aagentId\x12'\n" +
	"\x0fclaimed_version\x18\a \x01(\x03R\x0eclaimedVersion\x12\x1a\n" +
	"\bpriority\x18\b \x01(\x05R\bpriority\x12,\n" +
	"\x12composite_group_id\x18\t \x01(\tR\x10compositeGroupId\"p\n" +
	"\x17CompositeMutationIntent\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12:\n" +
	"\aintents\x18\x02 \x03(\v2 .polaris.protocol.MutationIntentR\aintents\"\xc4\x01\n" +
	"\fOutboxRecord\x12#\n" +
	"\rtarget_engine\x18\x01 \x01(\tR\ftargetEngine\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x05R\aversionB;Z9github.com/mrlaoliai/polaris-harness/internal/protocol/pbb\x06proto3"

var (
	file_mutation_proto_rawDescOnce sync.Once
	file_mutation_proto_rawDescData []byte
)

func file_mutation_proto_rawDescGZIP() []byte {
	file_mutation_proto_rawDescOnce.Do(func() {
		file_mutation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mutation_proto_rawDesc), len(file_mutation_proto_rawDesc)))
	})
	return file_mutation_proto_rawDescData
}

var file_mutation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mutation_proto_goTypes = []any{
	(*MutationIntent)(nil),          // 0: polaris.protocol.MutationIntent
	(*CompositeMutationIntent)(nil), // 1: polaris.protocol.CompositeMutationIntent
	(*OutboxRecord)(nil),            // 2: polaris.protocol.OutboxRecord
}
var file_mutation_proto_depIdxs = []int32{
	0, // 0: polaris.protocol.CompositeMutationIntent.intents:type_name -> polaris.protocol.MutationIntent
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mutation_proto_init() }
func file_mutation_proto_init() {
	if File_mutation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mutation_proto_rawDesc), len(file_mutation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mutation_proto_goTypes,
		DependencyIndexes: file_mutation_proto_depIdxs,
		MessageInfos:      file_mutation_proto_msgTypes,
	}.Build()
	File_mutation_proto = out.File
	file_mutation_proto_goTypes = nil
	file_mutation_proto_depIdxs = nil
}
